[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver"
version = "0.16.0"
update_changelog_on_bump = true
major_version_zero = true

version_files = [
    "WijnProject/__init__.py",
]

post_bump_hooks=[
  "build\\push_all.cmd"
]
