# Generated by Django 5.2.1 on 2025-05-26 17:35

import WijnVoorraad.models
import datetime
import django.db.models.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("WijnVoorraad", "0001_initial"),
        ("WijnVoorraad", "0002_druivensoort_alter_wijnsoort_options"),
        ("WijnVoorraad", "0003_deelnemer"),
        ("WijnVoorraad", "0004_locatie_vak"),
        ("WijnVoorraad", "0005_alter_vak_options"),
        ("WijnVoorraad", "0006_remove_vak_omschrijving_and_more"),
        ("WijnVoorraad", "0007_wijn"),
        ("WijnVoorraad", "0008_alter_druivensoort_options_alter_wijn_options_and_more"),
        ("WijnVoorraad", "0009_alter_wijn_jaar"),
        (
            "WijnVoorraad",
            "0010_wijn_classificatie_wijn_leverancier_wijn_opmerking_and_more",
        ),
        ("WijnVoorraad", "0011_alter_wijndruivensoort_options_and_more"),
        ("WijnVoorraad", "0012_alter_wijn_wijnsoort_and_more"),
        ("WijnVoorraad", "0013_voorraadmutatie"),
        ("WijnVoorraad", "0014_alter_voorraadmutatie_options_vak_capaciteit"),
        ("WijnVoorraad", "0015_wijnvoorraad_unique_wijnvoorraad"),
        ("WijnVoorraad", "0016_alter_wijnvoorraad_options"),
        ("WijnVoorraad", "0017_wijn_unique_wijn"),
        ("WijnVoorraad", "0018_deelnemer_standaardlocatie_deelnemeruser_and_more"),
        ("WijnVoorraad", "0019_remove_voorraadmutatie_deelnemer_and_more"),
        ("WijnVoorraad", "0020_alter_voorraadmutatie_aankoop_and_more"),
        ("WijnVoorraad", "0021_remove_aankoop_aantal_and_more"),
        ("WijnVoorraad", "0022_alter_voorraadmutatie_locatie"),
        ("WijnVoorraad", "0023_alter_voorraadmutatie_omschrijving"),
        (
            "WijnVoorraad",
            "0024_rename_aankoop_ontvangst_alter_ontvangst_options_and_more",
        ),
        ("WijnVoorraad", "0025_ontvangst_prijs_alter_wijnvoorraad_ontvangst"),
        (
            "WijnVoorraad",
            "0026_alter_ontvangst_options_alter_ontvangst_leverancier_and_more",
        ),
        ("WijnVoorraad", "0027_alter_wijn_wijndruivensoorten"),
        ("WijnVoorraad", "0028_wijn_foto_alter_ontvangst_datumontvangst"),
        (
            "WijnVoorraad",
            "0029_alter_deelnemer_naam_alter_druivensoort_omschrijving_and_more",
        ),
        ("WijnVoorraad", "0030_alter_deelnemer_users"),
        ("WijnVoorraad", "0031_alter_deelnemer_users_delete_deelnemeruser"),
        ("WijnVoorraad", "0032_remove_deelnemer_users"),
        ("WijnVoorraad", "0033_deelnemeruser_deelnemeruser_unique_deelnemer_user"),
        ("WijnVoorraad", "0034_delete_deelnemeruser"),
        ("WijnVoorraad", "0035_deelnemer_users"),
        ("WijnVoorraad", "0036_alter_deelnemer_users"),
        ("WijnVoorraad", "0037_locatie_aantal_kolommen"),
        ("WijnVoorraad", "0038_alter_wijn_options_remove_wijn_leverancier"),
        ("WijnVoorraad", "0039_remove_wijn_unique_wijn_wijn_unique_wijn"),
        ("WijnVoorraad", "0040_alter_wijndruivensoort_wijn"),
        ("WijnVoorraad", "0041_alter_voorraadmutatie_ontvangst"),
        ("WijnVoorraad", "0042_convdeelnemer_convdeelnemer_uniquekey"),
        ("WijnVoorraad", "0043_alter_convdeelnemer_options_and_more"),
        ("WijnVoorraad", "0044_convdruivensoort"),
        ("WijnVoorraad", "0045_convlocatie"),
        ("WijnVoorraad", "0046_convwijn_alter_convdruivensoort_options"),
        ("WijnVoorraad", "0047_convwijndruivensoort_alter_convwijn_options_and_more"),
        ("WijnVoorraad", "0048_convvoorraadmutatie_and_more"),
        (
            "WijnVoorraad",
            "0049_remove_convvoorraadmutatie_uniquekey_voorraarmutatie_and_more",
        ),
        (
            "WijnVoorraad",
            "0050_remove_convvoorraadmutatie_uniquekey_voorraarmutatie_and_more",
        ),
        ("WijnVoorraad", "0051_delete_convvoorraadmutatie"),
        ("WijnVoorraad", "0052_convvoorraadmutatie_and_more"),
        ("WijnVoorraad", "0053_alter_convwijndruivensoort_options_and_more"),
        ("WijnVoorraad", "0054_alter_convvoorraadmutatie_datum_oud"),
        ("WijnVoorraad", "0055_alter_convvoorraadmutatie_options_and_more"),
        ("WijnVoorraad", "0056_alter_convvoorraadmutatie_options_and_more"),
        ("WijnVoorraad", "0057_alter_convvoorraadmutatie_id_oud"),
        ("WijnVoorraad", "0058_alter_convvoorraadmutatie_id_oud"),
        ("WijnVoorraad", "0059_aiusage"),
        ("WijnVoorraad", "0060_wijnsoort_omschrijving_engels_ai_and_more"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WijnSoort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("omschrijving", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["omschrijving"],
                "verbose_name": "wijnsoort",
                "verbose_name_plural": "wijnsoorten",
            },
        ),
        migrations.CreateModel(
            name="Deelnemer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["naam"],
            },
        ),
        migrations.CreateModel(
            name="Locatie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("omschrijving", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["omschrijving"],
            },
        ),
        migrations.CreateModel(
            name="Vak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                (
                    "locatie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WijnVoorraad.locatie",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "vakken",
                "ordering": ["locatie", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                        fields=("locatie", "code"),
                        name="unique_code_binnen_locatie",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DruivenSoort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("omschrijving", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "druivensoort",
                "verbose_name_plural": "druivensoorten",
                "ordering": ["omschrijving"],
            },
        ),
        migrations.CreateModel(
            name="Wijn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=200)),
                ("domein", models.CharField(max_length=200)),
                ("land", models.CharField(blank=True, max_length=200, null=True)),
                ("datumAangemaakt", models.DateTimeField(auto_now_add=True)),
                (
                    "wijnsoort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WijnVoorraad.wijnsoort",
                    ),
                ),
                ("datumAfgesloten", models.DateTimeField(blank=True, null=True)),
                (
                    "jaar",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[WijnVoorraad.models.Wijn.validate_jaartal],
                    ),
                ),
                (
                    "classificatie",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "leverancier",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("opmerking", models.CharField(blank=True, max_length=200, null=True)),
                ("streek", models.CharField(blank=True, max_length=200, null=True)),
                ("website", models.URLField(blank=True, null=True)),
            ],
            options={
                "ordering": ["naam"],
                "verbose_name_plural": "wijnen",
            },
        ),
        migrations.CreateModel(
            name="WijnDruivensoort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "druivensoort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WijnVoorraad.druivensoort",
                    ),
                ),
                (
                    "wijn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WijnVoorraad.wijn",
                    ),
                ),
            ],
            options={
                "ordering": ["wijn", "druivensoort"],
                "verbose_name_plural": "Wijn druivensoorten",
            },
        ),
        migrations.AddField(
            model_name="wijn",
            name="wijnDruivensoorten",
            field=models.ManyToManyField(
                through="WijnVoorraad.WijnDruivensoort", to="WijnVoorraad.druivensoort"
            ),
        ),
        migrations.AddConstraint(
            model_name="wijndruivensoort",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("wijn", "druivensoort"),
                name="unique_wijn_druivensoort",
            ),
        ),
        migrations.AlterField(
            model_name="wijn",
            name="wijnsoort",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="WijnVoorraad.wijnsoort"
            ),
        ),
        migrations.AlterField(
            model_name="wijndruivensoort",
            name="druivensoort",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="WijnVoorraad.druivensoort",
            ),
        ),
        migrations.AlterField(
            model_name="wijndruivensoort",
            name="wijn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="WijnVoorraad.wijn"
            ),
        ),
        migrations.CreateModel(
            name="VoorraadMutatie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "in_uit",
                    models.CharField(choices=[("I", "In"), ("U", "Uit")], max_length=1),
                ),
                ("datum", models.DateField()),
                ("aantal", models.IntegerField()),
                ("omschrijving", models.CharField(max_length=200)),
                (
                    "deelnemer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="WijnVoorraad.deelnemer",
                    ),
                ),
                (
                    "locatie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="WijnVoorraad.locatie",
                    ),
                ),
                (
                    "vak",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="WijnVoorraad.vak",
                    ),
                ),
                (
                    "wijn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="WijnVoorraad.wijn",
                    ),
                ),
            ],
            options={
                "verbose_name": "voorraadmutatie",
                "verbose_name_plural": "voorraadmutaties",
            },
        ),
        migrations.AddField(
            model_name="vak",
            name="capaciteit",
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name="WijnVoorraad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aantal", models.IntegerField(default=0)),
                (
                    "deelnemer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="WijnVoorraad.deelnemer",
                    ),
                ),
                (
                    "locatie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="WijnVoorraad.locatie",
                    ),
                ),
                (
                    "vak",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="WijnVoorraad.vak",
                    ),
                ),
                (
                    "wijn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="WijnVoorraad.wijn",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wijnvoorraad",
                "verbose_name_plural": "wijnvoorraad",
                "constraints": [
                    models.UniqueConstraint(
                        deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                        fields=("wijn", "deelnemer", "locatie", "vak"),
                        name="unique_wijnvoorraad",
                    )
                ],
                "ordering": ["wijn", "deelnemer", "locatie", "vak"],
            },
        ),
        migrations.AddConstraint(
            model_name="wijn",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("naam", "domein"),
                name="unique_wijn",
            ),
        ),
        migrations.AddField(
            model_name="deelnemer",
            name="standaardLocatie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="WijnVoorraad.locatie",
            ),
        ),
        migrations.CreateModel(
            name="DeelnemerUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deelnemer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WijnVoorraad.deelnemer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Deelnemer users",
                "ordering": ["deelnemer", "user"],
            },
        ),
        migrations.AddField(
            model_name="deelnemer",
            name="users",
            field=models.ManyToManyField(
                through="WijnVoorraad.DeelnemerUser", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="deelnemeruser",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("deelnemer", "user"),
                name="unique_deelnemer_user",
            ),
        ),
        migrations.RemoveField(
            model_name="voorraadmutatie",
            name="deelnemer",
        ),
        migrations.RemoveField(
            model_name="voorraadmutatie",
            name="locatie",
        ),
        migrations.RemoveField(
            model_name="voorraadmutatie",
            name="vak",
        ),
        migrations.RemoveField(
            model_name="voorraadmutatie",
            name="wijn",
        ),
        migrations.AddField(
            model_name="voorraadmutatie",
            name="vak",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="WijnVoorraad.vak",
            ),
        ),
        migrations.AddField(
            model_name="voorraadmutatie",
            name="locatie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="WijnVoorraad.locatie"
            ),
        ),
        migrations.CreateModel(
            name="Ontvangst",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datumOntvangst", models.DateField(default=datetime.datetime.now)),
                (
                    "leverancier",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("website", models.URLField(blank=True, default="")),
                ("opmerking", models.CharField(blank=True, default="", max_length=200)),
                (
                    "deelnemer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="WijnVoorraad.deelnemer",
                    ),
                ),
                (
                    "wijn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="WijnVoorraad.wijn",
                    ),
                ),
                (
                    "prijs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ontvangsten",
                "ordering": ["-datumOntvangst", "deelnemer", "wijn"],
            },
        ),
        migrations.AddField(
            model_name="wijnvoorraad",
            name="ontvangst",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="WijnVoorraad.ontvangst"
            ),
        ),
        migrations.AddField(
            model_name="voorraadmutatie",
            name="ontvangst",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="WijnVoorraad.ontvangst"
            ),
        ),
        migrations.AddField(
            model_name="voorraadmutatie",
            name="actie",
            field=models.CharField(
                choices=[
                    ("K", "Koop"),
                    ("O", "Ontvangst"),
                    ("V", "Verplaatsing"),
                    ("D", "Drink"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="voorraadmutatie",
            name="omschrijving",
            field=models.CharField(blank=True, default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wijn",
            name="classificatie",
            field=models.CharField(blank=True, default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wijn",
            name="land",
            field=models.CharField(blank=True, default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wijn",
            name="leverancier",
            field=models.CharField(blank=True, default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wijn",
            name="opmerking",
            field=models.CharField(blank=True, default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wijn",
            name="streek",
            field=models.CharField(blank=True, default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wijn",
            name="website",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wijn",
            name="wijnDruivensoorten",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                through="WijnVoorraad.WijnDruivensoort",
                to="WijnVoorraad.druivensoort",
            ),
        ),
        migrations.AddField(
            model_name="wijn",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="deelnemer",
            name="naam",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="druivensoort",
            name="omschrijving",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="locatie",
            name="omschrijving",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="wijnsoort",
            name="omschrijving",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.RemoveField(
            model_name="deelnemer",
            name="users",
        ),
        migrations.DeleteModel(
            name="DeelnemerUser",
        ),
        migrations.AddField(
            model_name="deelnemer",
            name="users",
            field=models.ManyToManyField(
                related_name="deelnemers",
                related_query_name="deelnemer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="locatie",
            name="aantal_kolommen",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterModelOptions(
            name="wijn",
            options={"ordering": ["domein", "naam"], "verbose_name_plural": "wijnen"},
        ),
        migrations.RemoveField(
            model_name="wijn",
            name="leverancier",
        ),
        migrations.RemoveConstraint(
            model_name="wijn",
            name="unique_wijn",
        ),
        migrations.AddConstraint(
            model_name="wijn",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("naam", "domein", "jaar"),
                name="unique_wijn",
            ),
        ),
        migrations.AlterField(
            model_name="wijndruivensoort",
            name="wijn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="WijnVoorraad.wijn"
            ),
        ),
        migrations.AlterField(
            model_name="voorraadmutatie",
            name="ontvangst",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="WijnVoorraad.ontvangst"
            ),
        ),
        migrations.CreateModel(
            name="ConvDeelnemer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_oud", models.BigIntegerField(unique=True)),
                ("id_nieuw", models.BigIntegerField()),
            ],
            options={
                "constraints": [],
                "ordering": ["id_oud"],
            },
        ),
        migrations.CreateModel(
            name="ConvLocatie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_oud", models.BigIntegerField(unique=True)),
                ("id_nieuw", models.BigIntegerField()),
            ],
            options={
                "ordering": ["id_oud"],
            },
        ),
        migrations.CreateModel(
            name="ConvDruivenSoort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_oud", models.BigIntegerField(unique=True)),
                ("id_nieuw", models.BigIntegerField()),
            ],
            options={
                "ordering": ["id_oud"],
                "verbose_name": "Conv druivensoort",
                "verbose_name_plural": "Conv druivensoorten",
            },
        ),
        migrations.CreateModel(
            name="ConvWijn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_oud", models.BigIntegerField(unique=True)),
                ("id_nieuw", models.BigIntegerField()),
            ],
            options={
                "ordering": ["id_oud"],
                "verbose_name_plural": "Conv wijnen",
            },
        ),
        migrations.CreateModel(
            name="ConvWijnDruivensoort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_wijn_oud", models.BigIntegerField()),
                ("id_druivensoort_oud", models.BigIntegerField()),
                ("id_nieuw", models.BigIntegerField()),
            ],
            options={
                "ordering": ["id_wijn_oud", "id_druivensoort_oud"],
                "constraints": [
                    models.UniqueConstraint(
                        deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                        fields=("id_wijn_oud", "id_druivensoort_oud"),
                        name="uniquekey_convwijndruivensoort",
                    )
                ],
                "verbose_name": "Conv wijn druivensoort",
                "verbose_name_plural": "Conv wijn druivensoorten",
            },
        ),
        migrations.CreateModel(
            name="ConvVoorraadmutatie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_nieuw", models.BigIntegerField()),
                ("id_oud", models.BigIntegerField(default=1, unique=True)),
            ],
            options={
                "ordering": ["id_oud"],
                "constraints": [],
            },
        ),
        migrations.CreateModel(
            name="AIUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=200)),
                ("response_time", models.DateTimeField()),
                ("response_content", models.TextField()),
                ("response_tokens_used", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="wijnsoort",
            name="omschrijving_engels_ai",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="wijnsoort",
            name="style_css_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("wijnsoort_rood", "wijnsoort_rood"),
                    ("wijnsoort_wit", "wijnsoort_wit"),
                    ("wijnsoort_rose", "wijnsoort_rose"),
                    ("wijnsoort_mousserend", "wijnsoort_mousserend"),
                    ("wijnsoort_rodeport", "wijnsoort_rodeport"),
                    ("wijnsoort_witteport", "wijnsoort_witteport"),
                ],
                max_length=100,
            ),
        ),
    ]
