# Generated by Django 4.1.7 on 2023-04-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DruivenSoort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omschrijving', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Druivensoort',
                'verbose_name_plural': 'druivensoorten',
                'ordering': ['omschrijving'],
            },
        ),
        migrations.AlterModelOptions(
            name='wijnsoort',
            options={'ordering': ['omschrijving'], 'verbose_name': 'wijnsoort', 'verbose_name_plural': 'wijnsoorten'},
        ),
    ]
