# Generated by Django 4.1.7 on 2023-04-07 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0003_deelnemer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omschrijving', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['omschrijving'],
            },
        ),
        migrations.CreateModel(
            name='Vak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('omschrijving', models.CharField(max_length=200)),
                ('locatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WijnVoorraad.locatie')),
            ],
            options={
                'verbose_name_plural': 'vakken',
                'ordering': ['omschrijving'],
            },
        ),
    ]
