# Generated by Django 4.1.7 on 2023-04-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0004_locatie_vak'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vak',
            options={'ordering': ['locatie', 'code'], 'verbose_name_plural': 'vakken'},
        ),
    ]
