# Generated by Django 4.1.7 on 2023-04-08 12:38

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0005_alter_vak_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vak',
            name='omschrijving',
        ),
        migrations.AddConstraint(
            model_name='vak',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('locatie', 'code'), name='unique_code_binnen_locatie'),
        ),
    ]
