# Generated by Django 4.1.7 on 2023-04-08 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0006_remove_vak_omschrijving_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wijn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=200)),
                ('domein', models.CharField(max_length=200)),
                ('land', models.CharField(max_length=200)),
                ('datumAangemaakt', models.DateTimeField(auto_now_add=True)),
                ('wijnsoort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WijnVoorraad.wijnsoort')),
            ],
            options={
                'ordering': ['naam'],
            },
        ),
    ]
