# Generated by Django 4.1.7 on 2023-04-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0007_wijn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='druivensoort',
            options={'ordering': ['omschrijving'], 'verbose_name': 'druivensoort', 'verbose_name_plural': 'druivensoorten'},
        ),
        migrations.AlterModelOptions(
            name='wijn',
            options={'ordering': ['naam'], 'verbose_name_plural': 'wijnen'},
        ),
        migrations.AddField(
            model_name='wijn',
            name='datumAfgesloten',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wijn',
            name='jaar',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wijn',
            name='land',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
