# Generated by Django 4.1.7 on 2023-04-08 16:29

import WijnVoorraad.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0008_alter_druivensoort_options_alter_wijn_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wijn',
            name='jaar',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[WijnVoorraad.models.Wijn.validate_jaartal]),
        ),
    ]
