# Generated by Django 4.1.7 on 2023-04-10 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0009_alter_wijn_jaar'),
    ]

    operations = [
        migrations.AddField(
            model_name='wijn',
            name='classificatie',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wijn',
            name='leverancier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wijn',
            name='opmerking',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wijn',
            name='streek',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wijn',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WijnDruivensoort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('druivensoort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WijnVoorraad.druivensoort')),
                ('wijn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WijnVoorraad.wijn')),
            ],
        ),
        migrations.AddField(
            model_name='wijn',
            name='wijnDruivensoorten',
            field=models.ManyToManyField(through='WijnVoorraad.WijnDruivensoort', to='WijnVoorraad.druivensoort'),
        ),
    ]
