# Generated by Django 4.1.7 on 2023-04-10 18:29

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0010_wijn_classificatie_wijn_leverancier_wijn_opmerking_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wijndruivensoort',
            options={'ordering': ['wijn', 'druivensoort'], 'verbose_name_plural': 'Wijn druivensoorten'},
        ),
        migrations.AddConstraint(
            model_name='wijndruivensoort',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('wijn', 'druivensoort'), name='unique_wijn_druivensoort'),
        ),
    ]
