# Generated by Django 4.1.7 on 2023-04-10 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0011_alter_wijndruivensoort_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wijn',
            name='wijnsoort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WijnVoorraad.wijnsoort'),
        ),
        migrations.AlterField(
            model_name='wijndruivensoort',
            name='druivensoort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WijnVoorraad.druivensoort'),
        ),
        migrations.AlterField(
            model_name='wijndruivensoort',
            name='wijn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WijnVoorraad.wijn'),
        ),
        migrations.CreateModel(
            name='WijnVoorraad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aantal', models.IntegerField(default=0)),
                ('deelnemer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WijnVoorraad.deelnemer')),
                ('locatie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WijnVoorraad.locatie')),
                ('vak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='WijnVoorraad.vak')),
                ('wijn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WijnVoorraad.wijn')),
            ],
            options={
                'verbose_name': 'Wijnvoorraad',
                'verbose_name_plural': 'wijnvoorraad',
            },
        ),
    ]
