# Generated by Django 4.1.7 on 2023-04-10 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0012_alter_wijn_wijnsoort_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoorraadMutatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_uit', models.CharField(choices=[('I', 'In'), ('U', 'Uit')], max_length=1)),
                ('datum', models.DateField()),
                ('aantal', models.IntegerField()),
                ('omschrijving', models.CharField(max_length=200)),
                ('deelnemer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WijnVoorraad.deelnemer')),
                ('locatie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WijnVoorraad.locatie')),
                ('vak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='WijnVoorraad.vak')),
                ('wijn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WijnVoorraad.wijn')),
            ],
            options={
                'verbose_name': 'voorraadmutatie',
                'verbose_name_plural': 'voorraadmuaties',
            },
        ),
    ]
