# Generated by Django 4.1.7 on 2023-04-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0013_voorraadmutatie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voorraadmutatie',
            options={'verbose_name': 'voorraadmutatie', 'verbose_name_plural': 'voorraadmutaties'},
        ),
        migrations.AddField(
            model_name='vak',
            name='capaciteit',
            field=models.IntegerField(default=1),
        ),
    ]
