# Generated by Django 4.1.7 on 2023-04-12 13:16

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0014_alter_voorraadmutatie_options_vak_capaciteit'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wijnvoorraad',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('wijn', 'deelnemer', 'locatie', 'vak'), name='unique_wijnvoorraad'),
        ),
    ]
