# Generated by Django 4.1.7 on 2023-04-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0015_wijnvoorraad_unique_wijnvoorraad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wijnvoorraad',
            options={'ordering': ['wijn', 'deelnemer', 'locatie', 'vak'], 'verbose_name': 'Wijnvoorraad', 'verbose_name_plural': 'wijnvoorraad'},
        ),
    ]
