# Generated by Django 4.1.7 on 2023-04-12 13:38

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0016_alter_wijnvoorraad_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wijn',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('naam', 'domein'), name='unique_wijn'),
        ),
    ]
