# Generated by Django 4.1.7 on 2023-05-13 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0018_deelnemer_standaardlocatie_deelnemeruser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voorraadmutatie',
            name='deelnemer',
        ),
        migrations.RemoveField(
            model_name='voorraadmutatie',
            name='locatie',
        ),
        migrations.RemoveField(
            model_name='voorraadmutatie',
            name='vak',
        ),
        migrations.RemoveField(
            model_name='voorraadmutatie',
            name='wijn',
        ),
        migrations.AddField(
            model_name='voorraadmutatie',
            name='actie',
            field=models.CharField(blank=True, choices=[('K', 'Koop'), ('V', 'Verplaatsing'), ('D', 'Drink')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='voorraadmutatie',
            name='voorraad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='WijnVoorraad.wijnvoorraad'),
        ),
        migrations.CreateModel(
            name='Aankoop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datumAankoop', models.DateField()),
                ('aantal', models.IntegerField()),
                ('leverancier', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('opmerking', models.CharField(blank=True, max_length=200, null=True)),
                ('deelnemer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WijnVoorraad.deelnemer')),
                ('wijn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WijnVoorraad.wijn')),
            ],
            options={
                'verbose_name_plural': 'aankopen',
                'ordering': ['deelnemer', 'wijn', 'datumAankoop'],
            },
        ),
        migrations.AddField(
            model_name='voorraadmutatie',
            name='aankoop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='WijnVoorraad.aankoop'),
        ),
    ]
