# Generated by Django 4.1.7 on 2023-05-13 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0020_alter_voorraadmutatie_aankoop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aankoop',
            name='aantal',
        ),
        migrations.RemoveField(
            model_name='voorraadmutatie',
            name='voorraad',
        ),
        migrations.AddField(
            model_name='voorraadmutatie',
            name='locatie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='WijnVoorraad.locatie'),
        ),
        migrations.AddField(
            model_name='voorraadmutatie',
            name='vak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='WijnVoorraad.vak'),
        ),
        migrations.AlterField(
            model_name='voorraadmutatie',
            name='aankoop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WijnVoorraad.aankoop'),
        ),
    ]
