# Generated by Django 4.1.7 on 2023-05-13 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0021_remove_aankoop_aantal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voorraadmutatie',
            name='locatie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WijnVoorraad.locatie'),
        ),
    ]
