# Generated by Django 4.1.7 on 2023-05-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0022_alter_voorraadmutatie_locatie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voorraadmutatie',
            name='omschrijving',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
