# Generated by Django 4.1.7 on 2023-05-14 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0024_rename_aankoop_ontvangst_alter_ontvangst_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontvangst',
            name='prijs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='wijnvoorraad',
            name='ontvangst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WijnVoorraad.ontvangst'),
        ),
    ]
