# Generated by Django 4.1.7 on 2023-06-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0026_alter_ontvangst_options_alter_ontvangst_leverancier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wijn',
            name='wijnDruivensoorten',
            field=models.ManyToManyField(blank=True, null=True, through='WijnVoorraad.WijnDruivensoort', to='WijnVoorraad.druivensoort'),
        ),
    ]
