# Generated by Django 4.1.7 on 2023-07-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0028_wijn_foto_alter_ontvangst_datumontvangst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deelnemer',
            name='naam',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='druivensoort',
            name='omschrijving',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='locatie',
            name='omschrijving',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='wijnsoort',
            name='omschrijving',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
