# Generated by Django 4.1.7 on 2023-07-25 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WijnVoorraad', '0029_alter_deelnemer_naam_alter_druivensoort_omschrijving_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deelnemer',
            name='users',
            field=models.ManyToManyField(related_name='deelnemers', through='WijnVoorraad.DeelnemerUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
