# Generated by Django 4.1.7 on 2023-07-25 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0031_alter_deelnemer_users_delete_deelnemeruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deelnemer',
            name='users',
        ),
    ]
