# Generated by Django 4.1.7 on 2023-07-25 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WijnVoorraad', '0032_remove_deelnemer_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeelnemerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deelnemer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WijnVoorraad.deelnemer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Deelnemer users',
                'ordering': ['deelnemer', 'user'],
            },
        ),
        migrations.AddConstraint(
            model_name='deelnemeruser',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('deelnemer', 'user'), name='unique_deelnemer_user'),
        ),
    ]
