# Generated by Django 4.1.7 on 2023-07-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0033_deelnemeruser_deelnemeruser_unique_deelnemer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeelnemerUser',
        ),
    ]
