# Generated by Django 4.1.7 on 2024-05-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0037_locatie_aantal_kolommen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wijn',
            options={'ordering': ['domein', 'naam'], 'verbose_name_plural': 'wijnen'},
        ),
        migrations.RemoveField(
            model_name='wijn',
            name='leverancier',
        ),
    ]
