# Generated by Django 4.1.7 on 2024-05-08 14:57

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0038_alter_wijn_options_remove_wijn_leverancier'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wijn',
            name='unique_wijn',
        ),
        migrations.AddConstraint(
            model_name='wijn',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('naam', 'domein', 'jaar'), name='unique_wijn'),
        ),
    ]
