# Generated by Django 4.1.7 on 2024-05-10 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0039_remove_wijn_unique_wijn_wijn_unique_wijn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wijndruivensoort',
            name='wijn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WijnVoorraad.wijn'),
        ),
    ]
