# Generated by Django 4.1.7 on 2024-05-10 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0040_alter_wijndruivensoort_wijn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voorraadmutatie',
            name='ontvangst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WijnVoorraad.ontvangst'),
        ),
    ]
