# Generated by Django 4.1.7 on 2024-06-15 19:04

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0041_alter_voorraadmutatie_ontvangst'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvDeelnemer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_oud', models.BigIntegerField()),
                ('id_nieuw', models.BigIntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='convdeelnemer',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('id_oud', 'id_nieuw'), name='uniquekey'),
        ),
    ]
