# Generated by Django 4.1.7 on 2024-06-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0042_convdeelnemer_convdeelnemer_uniquekey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convdeelnemer',
            options={'ordering': ['id_oud']},
        ),
        migrations.RemoveConstraint(
            model_name='convdeelnemer',
            name='uniquekey',
        ),
        migrations.AlterField(
            model_name='convdeelnemer',
            name='id_oud',
            field=models.BigIntegerField(unique=True),
        ),
    ]
