# Generated by Django 4.1.7 on 2024-06-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0043_alter_convdeelnemer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvDruivenSoort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_oud', models.BigIntegerField(unique=True)),
                ('id_nieuw', models.BigIntegerField()),
            ],
            options={
                'ordering': ['id_oud'],
            },
        ),
    ]
