# Generated by Django 4.1.7 on 2024-06-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0045_convlocatie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvWijn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_oud', models.BigIntegerField(unique=True)),
                ('id_nieuw', models.BigIntegerField()),
            ],
            options={
                'ordering': ['id_oud'],
            },
        ),
        migrations.AlterModelOptions(
            name='convdruivensoort',
            options={'ordering': ['id_oud'], 'verbose_name': 'Conv druivensoort', 'verbose_name_plural': 'Conv druivensoorten'},
        ),
    ]
