# Generated by Django 4.1.7 on 2024-06-23 12:40

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0047_convwijndruivensoort_alter_convwijn_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvVoorraadmutatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_wijn_oud', models.BigIntegerField()),
                ('id_deelnemer_oud', models.BigIntegerField()),
                ('id_locatie_oud', models.BigIntegerField()),
                ('indicatie_in_uit_oud', models.CharField(max_length=1)),
                ('datum_oud', models.DateField()),
                ('id_nieuw', models.BigIntegerField()),
            ],
            options={
                'ordering': ['id_wijn_oud', 'id_deelnemer_oud', 'id_locatie_oud', 'indicatie_in_uit_oud', 'datum_oud'],
            },
        ),
        migrations.AddConstraint(
            model_name='convvoorraadmutatie',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('id_wijn_oud', 'id_deelnemer_oud', 'id_locatie_out', 'indicatie_in_uit_oud', 'datum_oud'), name='uniquekey_voorraarmutatie'),
        ),
    ]
