# Generated by Django 4.1.7 on 2024-06-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0055_alter_convvoorraadmutatie_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convvoorraadmutatie',
            options={'ordering': ['id_oud']},
        ),
        migrations.AlterField(
            model_name='convvoorraadmutatie',
            name='id_oud',
            field=models.BigIntegerField(),
        ),
    ]
