# Generated by Django 4.1.7 on 2024-06-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0057_alter_convvoorraadmutatie_id_oud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convvoorraadmutatie',
            name='id_oud',
            field=models.BigIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
