# Generated by Django 4.1.7 on 2025-04-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0059_aiusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='wijnsoort',
            name='omschrijving_engels_ai',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='wijnsoort',
            name='style_css_class',
            field=models.CharField(blank=True, choices=[('wijnsoort_rood', 'wijnsoort_rood'), ('wijnsoort_wit', 'wijnsoort_wit'), ('wijnsoort_rose', 'wijnsoort_rose'), ('wijnsoort_mousserend', 'wijnsoort_mousserend'), ('wijnsoort_rodeport', 'wijnsoort_rodeport'), ('wijnsoort_witteport', 'wijnsoort_witteport')], max_length=100),
        ),
    ]
