# Generated by Django 4.1.7 on 2025-04-13 14:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0060_wijnsoort_omschrijving_engels_ai_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bestelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datumAangemaakt', models.DateField(default=datetime.datetime.now)),
                ('opmerking', models.CharField(blank=True, max_length=200)),
                ('datumAfgesloten', models.DateTimeField(blank=True, null=True)),
                ('deelnemer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WijnVoorraad.deelnemer')),
                ('vanLocatie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WijnVoorraad.locatie')),
            ],
            options={
                'verbose_name_plural': 'bestellingen',
                'ordering': ['-datumAangemaakt', 'deelnemer', 'vanLocatie'],
            },
        ),
        migrations.CreateModel(
            name='BestellingRegel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aantal', models.IntegerField(default=0)),
                ('opmerking', models.CharField(blank=True, max_length=200)),
                ('bestelling', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WijnVoorraad.bestelling')),
                ('ontvangst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WijnVoorraad.ontvangst')),
                ('vak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='WijnVoorraad.vak')),
            ],
            options={
                'verbose_name_plural': 'bestellingregels',
                'ordering': ['bestelling', 'ontvangst'],
            },
        ),
        migrations.DeleteModel(
            name='ConvDeelnemer',
        ),
        migrations.DeleteModel(
            name='ConvDruivenSoort',
        ),
        migrations.DeleteModel(
            name='ConvLocatie',
        ),
        migrations.DeleteModel(
            name='ConvVoorraadmutatie',
        ),
        migrations.DeleteModel(
            name='ConvWijn',
        ),
        migrations.DeleteModel(
            name='ConvWijnDruivensoort',
        ),
    ]
