# Generated by Django 4.1.7 on 2025-04-22 19:47

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0061_bestelling_bestellingregel_delete_convdeelnemer_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bestellingregel',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('bestelling', 'ontvangst', 'vak'), name='unique_bestellingregel'),
        ),
    ]
