# Generated by Django 4.1.7 on 2025-04-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0064_bestellingregel_aantal_correctie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestellingregel',
            name='aantal_correctie',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
