# Generated by Django 4.1.7 on 2025-05-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0065_alter_bestellingregel_aantal_correctie'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestellingregel',
            name='verwerkt',
            field=models.CharField(choices=[('N', ''), ('A', 'Afgeboekt'), ('V', 'Verplaatst')], default='N', max_length=1),
        ),
    ]
