# Generated by Django 4.1.7 on 2025-05-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0066_bestellingregel_verwerkt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voorraadmutatie',
            name='actie',
            field=models.CharField(choices=[('K', 'Koop'), ('O', 'Ontvangst'), ('V', 'Verplaatsing'), ('D', 'Drink'), ('A', 'Afboeking')], max_length=1),
        ),
    ]
