# Generated by Django 5.2.1 on 2025-05-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0067_alter_voorraadmutatie_actie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontvangst',
            name='leverancier',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ontvangst',
            name='opmerking',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ontvangst',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='wijn',
            name='wijnDruivensoorten',
            field=models.ManyToManyField(blank=True, null=True, through='WijnVoorraad.WijnDruivensoort', through_fields=('wijn', 'druivensoort'), to='WijnVoorraad.druivensoort'),
        ),
    ]
