# Generated by Django 5.2.1 on 2025-05-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0068_alter_ontvangst_leverancier_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vak',
            name='unique_code_binnen_locatie',
        ),
        migrations.AddConstraint(
            model_name='vak',
            constraint=models.UniqueConstraint(fields=('locatie', 'code'), name='unique_code_binnen_locatie'),
        ),
    ]
