# Generated by Django 5.2.1 on 2025-05-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0069_remove_vak_unique_code_binnen_locatie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wijn',
            options={'ordering': ['jaar', 'domein', 'naam'], 'verbose_name_plural': 'wijnen'},
        ),
        migrations.RemoveConstraint(
            model_name='wijn',
            name='unique_wijn',
        ),
        migrations.AddConstraint(
            model_name='wijn',
            constraint=models.UniqueConstraint(fields=('naam', 'domein', 'jaar'), name='unique_wijn'),
        ),
    ]
