# Generated by Django 5.2.1 on 2025-05-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0070_alter_wijn_options_remove_wijn_unique_wijn_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wijn',
            options={'ordering': [models.OrderBy(models.F('jaar'), nulls_last=True), 'domein', 'naam'], 'verbose_name_plural': 'wijnen'},
        ),
    ]
