# Generated by Django 5.2.1 on 2025-05-30 13:46

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0071_alter_wijn_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wijn',
            options={'ordering': [models.OrderBy(models.F('jaar'), nulls_last=True), django.db.models.functions.text.Lower('domein'), django.db.models.functions.text.Lower('naam')], 'verbose_name_plural': 'wijnen'},
        ),
    ]
