# Generated by Django 5.2.1 on 2025-06-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0072_alter_wijn_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wijnvoorraad',
            name='unique_wijnvoorraad',
        ),
        migrations.AddConstraint(
            model_name='wijnvoorraad',
            constraint=models.UniqueConstraint(fields=('ontvangst', 'locatie', 'vak'), name='unique_wijnvoorraad'),
        ),
    ]
