# Generated by Django 5.2.1 on 2025-06-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0073_remove_wijnvoorraad_unique_wijnvoorraad_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wijndruivensoort',
            name='unique_wijn_druivensoort',
        ),
        migrations.AddConstraint(
            model_name='wijndruivensoort',
            constraint=models.UniqueConstraint(fields=('wijn', 'druivensoort'), name='unique_wijn_druivensoort'),
        ),
    ]
