# Generated by Django 5.2.1 on 2025-06-08 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0074_remove_wijndruivensoort_unique_wijn_druivensoort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestelling',
            name='datumAangemaakt',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='bestelling',
            name='opmerking',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='bestellingregel',
            name='opmerking',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='ontvangst',
            name='datumOntvangst',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ontvangst',
            name='opmerking',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='wijn',
            name='opmerking',
            field=models.CharField(blank=True, max_length=4000),
        ),
    ]
