# Generated by Django 5.2.1 on 2025-06-18 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0075_alter_bestelling_datumaangemaakt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voorraadmutatie',
            options={'ordering': ['ontvangst', 'datum', 'in_uit'], 'verbose_name': 'voorraadmutatie', 'verbose_name_plural': 'voorraadmutaties'},
        ),
    ]
