# Generated by Django 5.2.1 on 2025-07-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WijnVoorraad', '0076_alter_voorraadmutatie_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestellingregel',
            name='opmerking',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
